# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25c23d3e366882b46de5984d2dc345221095b22bad0d5304db176c0e565eda99560ed7260978a3d7ddd946f56d7845a8e5b6345e3a650fd5a88a23d3d3a1a0eb

test:
  secret_key_base: 42974f7901f9c76f5b21e32ea828eac32688a6459d545ffc1b10a218dac704194d8f6468f637852983f120e403303e4365a1f6d8c6ce4d032392b608824e879e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
